import type { ClassDef } from '@/src/interfaces/structure'

export const signModel: ClassDef = {
  className: 'sign_model',
  description: '',
  attributes: [
    {
      key: 'sign_name',
      type: 'string',
      isArray: false,
      arrayElementType: undefined,
      description: 'Name from sign',
    },
    {
      key: 'model_desc',
      type: 'resource_tie',
      isArray: false,
      arrayElementType: undefined,
      description: '/path/to/file.pmd',
    },
    {
      key: 'model_coll',
      type: 'resource_tie',
      isArray: false,
      arrayElementType: undefined,
      description: '/path/to/file.pmc',
    },
    {
      key: 'look_name',
      type: ['token', 'string'],
      isArray: false,
      arrayElementType: undefined,
      description: '',
    },
    {
      key: 'variant_name',
      type: ['token', 'string'],
      isArray: false,
      arrayElementType: undefined,
      description: '',
    },
    {
      key: 'category',
      type: 'string',
      isArray: false,
      arrayElementType: undefined,
      description: '',
    },
    {
      key: 'dynamic',
      type: 'bool',
      isArray: false,
      arrayElementType: undefined,
      description: '',
    },
    {
      key: 'road_model',
      type: 'bool',
      isArray: false,
      arrayElementType: undefined,
      description: '',
    },
    {
      key: 'drop_sun_shadows',
      type: 'fixed',
      isArray: false,
      arrayElementType: undefined,
      description: '',
    },
    {
      key: 'mass',
      type: ['float', 'fixed'],
      isArray: false,
      arrayElementType: undefined,
      description: '',
    },
    {
      key: 'dynamic_lod_disc',
      type: 'fixed',
      isArray: true,
      arrayElementType: 'resource_tie',
      description: '/path/to/file.pmd',
    },
    {
      key: 'dynamic_lod_dist',
      type: 'fixed',
      isArray: true,
      arrayElementType: 'fixed',
      description: '',
    },
    {
      key: 'stand_classes',
      type: 'fixed',
      isArray: true,
      arrayElementType: ['token', 'string'],
      description: '',
    },
    {
      key: 'editable',
      type: 'bool',
      isArray: false,
      arrayElementType: undefined,
      description: '',
    },
    {
      key: 'boards',
      type: 'bool',
      isArray: false,
      arrayElementType: undefined,
      description: '',
    },
    {
      key: 'traffic_rule',
      type: ['token', 'string'],
      isArray: false,
      arrayElementType: undefined,
      description: '',
    },
    {
      key: 'traffic_rule_lane_count',
      type: 'fixed',
      isArray: false,
      arrayElementType: undefined,
      description: '',
    },
  ],
}
