import type { ClassDef } from '@/src/interfaces/structure'

export const multimonConfig: ClassDef = {
  className: 'multimon_config',
  description: '',
  attributes: [
    {
      key: 'normalized_ui_x',
      type: 'float',
      isArray: false,
      arrayElementType: undefined,
      description: '',
    },
    {
      key: 'normalized_ui_width',
      type: 'float',
      isArray: false,
      arrayElementType: undefined,
      description: '',
    },
    {
      key: 'monitors',
      type: 'fixed',
      isArray: true,
      arrayElementType: 'owner_ptr',
      description: '',
    },
    {
      key: 'name',
      type: 'string',
      isArray: false,
      arrayElementType: undefined,
      description: '',
    },
    {
      key: 'normalized_x',
      type: 'float',
      isArray: false,
      arrayElementType: undefined,
      description: '',
    },
    {
      key: 'normalized_y',
      type: 'float',
      isArray: false,
      arrayElementType: undefined,
      description: '',
    },
    {
      key: 'normalized_width',
      type: 'float',
      isArray: false,
      arrayElementType: undefined,
      description: '',
    },
    {
      key: 'normalized_height',
      type: 'float',
      isArray: false,
      arrayElementType: undefined,
      description: '',
    },
    {
      key: 'horizontal_fov_relative_offset',
      type: 'float',
      isArray: false,
      arrayElementType: undefined,
      description: '',
    },
    {
      key: 'vertical_fov_relative_offset',
      type: 'float',
      isArray: false,
      arrayElementType: undefined,
      description: '',
    },
    {
      key: 'heading_offset',
      type: 'float',
      isArray: false,
      arrayElementType: undefined,
      description: '',
    },
    {
      key: 'heading_offset',
      type: ['fixed', 'float'],
      isArray: false,
      arrayElementType: undefined,
      description: '',
    },
    {
      key: 'pitch_offset',
      type: ['fixed', 'float'],
      isArray: false,
      arrayElementType: undefined,
      description: '',
    },
    {
      key: 'roll_offset',
      type: ['fixed', 'float'],
      isArray: false,
      arrayElementType: undefined,
      description: '',
    },
    {
      key: 'camera_space_offset',
      type: ['fixed3', 'float3'],
      isArray: false,
      arrayElementType: undefined,
      description: '',
    },
    {
      key: 'horizontal_fov_override',
      type: 'float',
      isArray: false,
      arrayElementType: undefined,
      description: '',
    },
    {
      key: 'vertical_fov_override',
      type: 'float',
      isArray: false,
      arrayElementType: undefined,
      description: '',
    },
    {
      key: 'frustum_subrect_x',
      type: 'float',
      isArray: false,
      arrayElementType: undefined,
      description: '',
    },
    {
      key: 'frustum_subrect_y',
      type: 'float',
      isArray: false,
      arrayElementType: undefined,
      description: '',
    },
    {
      key: 'frustum_subrect_width',
      type: 'float',
      isArray: false,
      arrayElementType: undefined,
      description: '',
    },
    {
      key: 'frustum_subrect_height',
      type: 'float',
      isArray: false,
      arrayElementType: undefined,
      description: '',
    },
    {
      key: 'render_interior',
      type: 'bool',
      isArray: false,
      arrayElementType: undefined,
      description: '',
    },
    {
      key: 'render_exterior',
      type: 'bool',
      isArray: false,
      arrayElementType: undefined,
      description: '',
    },
  ],
}
